import { GenericFormFieldConfig } from "@/shared/config";
import { ORDER_STATUSES, OrderFilterSchemaType } from "./schemas";

export type FilterOrderFieldConfig = GenericFormFieldConfig<OrderFilterSchemaType>;

export const filterOrderConfig: FilterOrderFieldConfig[] = [
    {
        label: "Tìm kiếm",
        name: "keyword",
        type: "text",
        placeholder: "Tìm kiếm...",
        colSpan: 3,
        colSpanMd: 3,
    },
    {
        label: "Người tạo",
        name: "createdBy",
        type: "autocomplete",
        placeholder: "Tất cả",
        colSpan: 3,
        colSpanMd: 3,
    },
    {
        label: "Trạng thái",
        name: "status",
        type: "select",
        placeholder: "Tất cả",
        options: ORDER_STATUSES.map((status) => ({ value: status, label: status })),
        colSpan: 3,
        colSpanMd: 3,
    },
    // {
    //     label: "Loại đơn hàng",
    //     name: "type",
    //     type: "select",
    //     placeholder: "Tất cả",
    //     options: [
    //         { value: "sale", label: "Bán hàng" },
    //         { value: "return", label: "Trả hàng" },
    //         { value: "purchase", label: "Mua hàng" },
    //     ],
    //     colSpan: 1,
    // },
    {
        label: "Ngày tạo",
        name: "startDate",
        type: "dateRange",
        minField: "startDate",
        maxField: "endDate",
        colSpan: 6,
        colSpanMd: 6,
    },
    {
        label: "Khoảng giá",
        name: "minTotalAmount",
        type: "numberRange",
        minField: "minTotalAmount",
        maxField: "maxTotalAmount",
        colSpan: 6,
        colSpanMd: 6,
    },
    {
        label: "Ngày hoàn thành",
        name: "completedStartDate",
        type: "dateRange",
        minField: "completedStartDate",
        maxField: "completedEndDate",
        colSpan: 6,
        colSpanMd: 6,
    },
    {
        label: "Phương thức thanh toán",
        name: "paymentMethods",
        type: "select",
        placeholder: "Tất cả",
        options: [
            { value: "cash", label: "Tiền mặt" },
            { value: "credit_card", label: "Thẻ tín dụng" },
            { value: "bank_transfer", label: "Chuyển khoản" },
        ],
        colSpan: 6,
        colSpanMd: 6,
    },
    {
        label: "Nhà sản xuất",
        name: "manufacturers",
        type: "autocomplete",
        placeholder: "Chọn nhà sản xuất...",
        colSpan: 6,
        colSpanMd: 6,
    },
    {
        label: "Dòng sản phẩm/Danh mục",
        name: "categories",
        type: "autocomplete",
        placeholder: "Tất cả",
        colSpan: 6,
        colSpanMd: 6,
    },
] as const;