export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_TEMPORARY_PASSWORD: '/auth/verify-temporary-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    ROOT: '/users',
    BY_EMAIL: (email: string) => `/users/email/${email}`,
    GET_PREFERENCES: '/users/get-preferences',
    EMAIL_PREFERENCES: '/users/email-preferences',
    BY_ID: (id: string) => `/users/${id}`,
    RESTORE: (id: string) => `/users/${id}/restore`,
  },
  ADMINISTRATIVE: {
    ROOT: '/administrative',
    BY_CODE: (code: string) => `/administrative/${code}`,
    RESTORE: (code: string) => `/administrative/${code}/restore`,
  },
  NOTIFICATIONS: {
    ROOT: '/notifications',
    MARK_ALL_READ: '/notifications/mark-all-read',
    BY_ID: (id: string) => `/notifications/${id}`,
    RESTORE: (id: string) => `/notifications/${id}/restore`,
  },
  WAREHOUSES: {
    ROOT: '/warehouses',
    BY_ID: (id: string) => `/warehouses/${id}`,
    RESTORE: (id: string) => `/warehouses/${id}/restore`,
  },
  CATEGORIES: {
    ROOT: '/categories',
    BY_ID: (id: string) => `/categories/${id}`,
    RESTORE: (id: string) => `/categories/${id}/restore`,
  },
  ORDERS: {
    ROOT: '/orders',
    STATUS_OPTIONS: '/orders/status-options',
    BULK_PAYMENT_PREVIEW: '/orders/bulk-payment-preview',
    BY_ID: (id: string) => `/orders/${id}`,
    EXPORT: (id: string) => `/orders/${id}/export`,
    PAYMENTS: (id: string) => `/orders/${id}/payments`,
    STATUS: (id: string) => `/orders/${id}/status`,
    RESTORE: (id: string) => `/orders/${id}/restore`,
    DETAILS: {
      ROOT: (orderId: string) => `/orders/${orderId}/details`,
      BY_ID: (orderId: string, detailId: string) => `/orders/${orderId}/details/${detailId}`,
    },
    TAGS: (id: string) => `/orders/${id}/tags`,
    HISTORY: (id: string) => `/orders/${id}/history`,
    BANKS: '/orders/banks', // Legacy/Integrated
  },
  PRODUCTS: {
    ROOT: '/products',
    EXPORT: '/products/export',
    IMPORT_EXCEL: '/products/import/excel',
    IMPORT_EXCEL_ASYNC: '/products/import/excel/async',
    IMPORT_STATUS: '/products/import/status',
    IMPORT_JOB_STATUS: (jobId: string) => `/products/import/status/${jobId}`,
    IMPORT_TEMPLATE: '/products/import/template',
    MANUFACTURERS: '/products/manufacturers',
    BY_ID: (id: string) => `/products/${id}`,
    BY_BARCODE: (barcode: string) => `/products/barcode/${barcode}`,
    RESTORE: (id: string) => `/products/${id}/restore`,
  },
  CUSTOMERS: {
    ROOT: '/customers',
    BY_ID: (id: string) => `/customers/${id}`,
    RESTORE: (id: string) => `/customers/${id}/restore`,
  },
  SUPPLIERS: {
    ROOT: '/suppliers',
    BY_ID: (id: string) => `/suppliers/${id}`,
    RESTORE: (id: string) => `/suppliers/${id}/restore`,
  },
  ROLES: {
    ROOT: '/roles',
    BY_ID: (id: string) => `/roles/${id}`,
    RESTORE: (id: string) => `/roles/${id}/restore`,
    ADMIN_GRANT_FULL_PERMISSIONS: '/roles/admin/grant-full-permissions',
    ADMIN_PERMISSIONS: '/roles/admin/permissions',
    PERMISSIONS: (id: string) => `/roles/${id}/permissions`,
  },
  HISTORY: {
    ROOT: '/history',
    BY_ENTITY: (entityType: string, entityId: string) => `/history/entity/${entityType}/${entityId}`,
  },
  STOCK_LEVELS: {
    ROOT: '/stock-levels',
    BY_ID: (id: string) => `/stock-levels/${id}`,
    RESTORE: (id: string) => `/stock-levels/${id}/restore`,
  },
  WAREHOUSE_RECEIPTS: {
    ROOT: '/warehouse-receipts',
    EXPORT: (id: string) => `/warehouse-receipts/${id}/export`,
    BY_ID: (id: string) => `/warehouse-receipts/${id}`,
    RESTORE: (id: string) => `/warehouse-receipts/${id}/restore`,
    REJECT: (id: string) => `/warehouse-receipts/${id}/reject`,
    APPROVE: (id: string) => `/warehouse-receipts/${id}/approve`,
    DETAILS: {
      ROOT: (receiptId: string) => `/warehouse-receipts/${receiptId}/details`,
      BY_ID: (receiptId: string, detailId: string) => `/warehouse-receipts/${receiptId}/details/${detailId}`,
    },
    IMPORT: {
      EXCEL: '/warehouse-receipts/import/excel',
      IMPORT: '/warehouse-receipts/import/import',
      EXPORT: '/warehouse-receipts/import/export',
      IMPORT_TEMPLATE: '/warehouse-receipts/import/import/template',
      EXPORT_TEMPLATE: '/warehouse-receipts/import/export/template',
      TEMPLATE: '/warehouse-receipts/import/template',
      EXCEL_ASYNC: '/warehouse-receipts/import/excel/async',
      IMPORT_ASYNC: '/warehouse-receipts/import/import/async',
      EXPORT_ASYNC: '/warehouse-receipts/import/export/async',
      STATUS: '/warehouse-receipts/import/status',
      JOB_STATUS: (jobId: string) => `/warehouse-receipts/import/status/${jobId}`,
    }
  },
  PAYMENTS: {
    ROOT: '/payments',
    MULTIPLE: '/payments/multiple',
    BY_ID: (id: string) => `/payments/${id}`,
    FILES: (paymentId: string) => `/payments/${paymentId}/files`,
  },
  DOCUMENT_TEMPLATES: {
    ROOT: '/document-templates',
    BY_ID: (id: string) => `/document-templates/${id}`,
    DEFAULT_VALUES: (id: string) => `/document-templates/${id}/default-values`,
  },
  TAGS: {
    ROOT: '/tags',
    BY_ID: (id: string) => `/tags/${id}`,
    RESTORE: (id: string) => `/tags/${id}/restore`,
    SYNC_FROM_ORDERS: '/tags/sync-from-orders',
  },
  QUOTATIONS: {
    ROOT: '/quotations',
    EXPORT: '/quotations/export',
    BY_ID_EXPORT: (id: string) => `/quotations/${id}/export`,
    BY_ID: (id: string) => `/quotations/${id}`,
    STATUS: (id: string) => `/quotations/${id}/status`,
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
    REVENUE_SERIES: '/dashboard/revenue-series',
    ORDER_STATUS: '/dashboard/order-status',
    INVENTORY_OVERVIEW: '/dashboard/inventory-overview',
    TOP_PRODUCTS: '/dashboard/top-products',
    TOP_CUSTOMERS: '/dashboard/top-customers',
    REGION_REVENUE: '/dashboard/region-revenue',
    CATEGORY_PROFIT: '/dashboard/category-profit',
    RECENT_ORDERS: '/dashboard/recent-orders',
    RECENT_ACTIVITIES: '/dashboard/recent-activities',
  },
  REPORT: {
    REVENUE: '/report/revenue',
  },
  FILES: {
    ASSETS: (path: string) => `/files/assets/${path}`,
    BY_PATH: (path: string) => `/files/${path}`,
  },
  PUBLIC: {
    TRANSLATIONS: '/public/translations',
    FAVICON: '/public/favicon.ico',
    LOGO: '/public/logo.png',
    OG_IMAGE: '/public/og-image.png',
  },
  BANKS: {
    ROOT: '/banks',
    LIST: '/banks/banks',
    BY_ID: (id: string) => `/banks/${id}`,
    RESTORE: (id: string) => `/banks/${id}/restore`,
  },
  SYSTEM_MIGRATE: {
    RECALCULATE_STOCK_LEVEL: '/system-migrate/recalculate-stock-level',
    ANALYZE_STOCK_LEVEL: '/system-migrate/analyze-stock-level',
    RECEIPTS_STATISTICS: '/system-migrate/receipts-statistics',
    DEBUG_RECEIPTS: '/system-migrate/debug-receipts',
  }
} as const;